// Turn a compiled plan into Nix source. Output is a standalone home-manager
// flake: portable, reproducible, applyable on any machine that has Nix.

const KNOWN_PROGRAMS = new Set(["zsh", "bash", "fish"]);

export function emitFlake(plan) {
  return `{
  description = "configtury-generated environment for ${plan.name}";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      system = "${plan.system}";
      pkgs = nixpkgs.legacyPackages.\${system};
    in {
      homeConfigurations."${plan.username}" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home.nix ];
      };
    };
}
`;
}

export function emitHome(plan) {
  const pkgList = plan.nixpkgs.map((p) => `    ${p}`).join("\n");

  let programs = "";
  if (plan.shell && KNOWN_PROGRAMS.has(plan.shell)) {
    programs = `\n  programs.${plan.shell}.enable = true;\n`;
  }

  return `# Generated by configtury. Edit the .toml spec and rebuild, don't hand-edit.
{ pkgs, ... }:
{
  home.username = "${plan.username}";
  home.homeDirectory = "${plan.homeDirectory}";
  home.stateVersion = "${plan.stateVersion}";

  home.packages = with pkgs; [
${pkgList}
  ];
${programs}}
`;
}

// ---- NixOS system target: the "closer to the metal" output ----

export function emitNixosFlake(plan) {
  return `{
  description = "configtury NixOS system: ${plan.name}";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { nixpkgs, ... }: {
    nixosConfigurations."${plan.name}" = nixpkgs.lib.nixosSystem {
      system = "${plan.system}";
      modules = [ ./configuration.nix ];
    };
  };
}
`;
}

function emitBoot(boot) {
  if (boot.loader === "grub") {
    return `  boot.loader.grub.enable = true;\n  boot.loader.grub.device = "${boot.device}";\n`;
  }
  // systemd-boot: the modern UEFI default.
  return `  boot.loader.systemd-boot.enable = true;\n  boot.loader.efi.canTouchEfiVariables = true;\n`;
}

function emitUsers(users) {
  if (!users.length) return "";
  const blocks = users
    .map((u) => {
      const groups = u.groups.map((g) => `"${g}"`).join(" ");
      return `  users.users.${u.name} = {
    isNormalUser = true;
    extraGroups = [ ${groups} ];
  };`;
    })
    .join("\n");
  return `\n${blocks}\n`;
}

export function emitConfiguration(plan) {
  const pkgList = plan.nixpkgs.map((p) => `    ${p}`).join("\n");
  const services = plan.services.map((attr) => `  ${attr} = true;`).join("\n");
  const pkgBlock = plan.nixpkgs.length
    ? `\n  environment.systemPackages = with pkgs; [\n${pkgList}\n  ];\n`
    : "";
  const serviceBlock = services ? `\n${services}\n` : "";

  return `# Generated by configtury. Edit the .toml spec and rebuild, don't hand-edit.
#
# NOTE: a bootable install also needs hardware specifics (fileSystems, swap,
# the boot device's filesystem). Those come from nixos-generate-config's
# hardware-configuration.nix today, or from a configtury disko layout once
# rung 2 lands. This file declares everything *above* the disk.
{ config, pkgs, ... }:
{
  networking.hostName = "${plan.name}";

${emitBoot(plan.boot)}${emitUsers(plan.users)}${pkgBlock}${serviceBlock}
  system.stateVersion = "${plan.stateVersion}";
}
`;
}
